[tool.poetry]
name = "xc-chatbot"
version = "0.1.0"
description = ""
authors = ["waqas <waqas.ahsan@fantechlabs.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
