# Use an official Python runtime as a parent image
FROM python:3.12

LABEL maintainer="Waqas"
# Set the working directory in the container
WORKDIR /code

# Install system dependencies required for potential Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# RUN apt update && apt install -y ffmpeg

# Install Poetry
RUN pip install poetry

# Copy the current directory contents into the container at /code
COPY . /code/

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenvs.create false

# Install dependencies including development ones
RUN poetry install

# install uvicorn and pydantic now in one line using pip
RUN pip install fastapi 
RUN pip install uvicorn 
RUN pip install pydantic 

# Make port 8000 available to the world outside this container
EXPOSE 8003

CMD ["python", "xc_chatbot/main.py"]


# CMD ["uvicorn", "xc_chatbot.main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]
